import ax1 from "../assets/games/AzureStrikerGunvolt.jpg";
import ax2 from "../assets/games/Braid.jpg";
import ax3 from "../assets/games/Castlevania Symphony of the Night.jpg";
import ax4 from "../assets/games/Cave Story.jpg";
import ax5 from "../assets/games/Celeste.jpg";
import ax6 from "../assets/games/Cuphead.jpg";
import ax7 from "../assets/games/Donkey Kong Country Tropical Freeze.jpg";
import ax8 from "../assets/games/Donkey Kong Jr.jpg";
import ax9 from "../assets/games/DuckTales.jpg";
import ax10 from "../assets/games/Hollow Knight.jpg";
import ax11 from "../assets/games/Inside.jpg";
import ax12 from "../assets/games/Kirby Super Star.jpg";
import ax13 from "../assets/games/Maga Man 1.jpg";
import ax14 from "../assets/games/Maga Man 2.jpg";
import ax15 from "../assets/games/Maga Man 3.jpg";
import ax16 from "../assets/games/Mega Man X.jpg";
import ax17 from "../assets/games/Ori and The Blind Forest.jpg";
import ax18 from "../assets/games/Rayman Legends.jpg";
import ax19 from "../assets/games/Shantae Half-Genie Hero.jpg";
import ax20 from "../assets/games/Shovel Knight.jpg";
import ax21 from "../assets/games/Sonic Mania.jpg";
import ax22 from "../assets/games/Sonic the Hedgehog.jpg";
import ax23 from "../assets/games/Street Fighter II Turbo.jpg";
import ax24 from "../assets/games/Super Castlevania IV.jpg";
import ax25 from "../assets/games/Super Ghouls and Ghosts.jpg";
import ax26 from "../assets/games/Super Mario Bros 3.jpg";
import ax27 from "../assets/games/Super Mario Land 2 The Six Golden Coins.jpg";
import ax28 from "../assets/games/Super Mario World.jpg";
import ax29 from "../assets/games/Super Meat Boy.jpg";
import ax30 from "../assets/games/Tetris.jpg";
import ax31 from "../assets/games/Unravel.jpg";
import ax32 from "../assets/games/Yoshi’s Island.jpg";

const books = [
  {
    id: "001",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Azure Striker Gunvolt",
    year: 0,
    img: ax1,
  },
  {
    id: "002",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Braid",
    year: 0,
    img: ax2,
  },
  {
    id: "003",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Castlevania Symphony of the Night",
    year: 0,
    img: ax3,
  },
  {
    id: "004",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Cave Story",
    year: 0,
    img: ax4,
  },
  {
    id: "005",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Celeste",
    year: 0,
    img: ax5,
  },
  {
    id: "006",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Cuphead",
    year: 0,
    img: ax6,
  },
  {
    id: "007",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Cuphead",
    year: 0,
    img: ax7,
  },
  {
    id: "008",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Donkey Kong Jr",
    year: 0,
    img: ax8,
  },
  {
    id: "009",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "DuckTales",
    year: 0,
    img: ax9,
  },
  {
    id: "010",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Hollow Knight",
    year: 0,
    img: ax10,
  },
  {
    id: "011",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Inside",
    year: 0,
    img: ax11,
  },
  {
    id: "012",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Kirby Super Star",
    year: 0,
    img: ax12,
  },
  {
    id: "013",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Maga Man 1",
    year: 0,
    img: ax13,
  },
  {
    id: "014",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Maga Man 2",
    year: 0,
    img: ax14,
  },
  {
    id: "015",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Maga Man 3",
    year: 0,
    img: ax15,
  },
  {
    id: "016",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Maga Man X",
    year: 0,
    img: ax16,
  },
  {
    id: "017",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Ori and The Blind Forest",
    year: 0,
    img: ax17,
  },
  {
    id: "018",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Rayman Legendst",
    year: 0,
    img: ax18,
  },
  {
    id: "019",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Shantae Half-Genie Hero",
    year: 0,
    img: ax19,
  },
  {
    id: "020",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Shovel Knight",
    year: 0,
    img: ax20,
  },
  {
    id: "021",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Sonic Mania",
    year: 0,
    img: ax21,
  },
  {
    id: "022",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Sonic the Hedgehog",
    year: 0,
    img: ax22,
  },
  {
    id: "023",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Street Fighter II Turbo",
    year: 0,
    img: ax23,
  },
  {
    id: "024",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Super Castlevania IV",
    year: 0,
    img: ax24,
  },
  {
    id: "025",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Super Ghouls and Ghosts",
    year: 0,
    img: ax25,
  },
  {
    id: "026",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Super Mario Bros 3",
    year: 0,
    img: ax26,
  },
  {
    id: "027",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Super Mario Land 2 The Six Golden Coins",
    year: 0,
    img: ax27,
  },
  {
    id: "028",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Super Mario World",
    year: 0,
    img: ax28,
  },
  {
    id: "029",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Super Meat Boy",
    year: 0,
    img: ax29,
  },
  {
    id: "030",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Tetris",
    year: 0,
    img: ax30,
  },
  {
    id: "031",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Unravel",
    year: 0,
    img: ax31,
  },
  {
    id: "032",
    author: "",
    country: "",
    language: "",
    link: "",
    pages: 0,
    title: "Yoshi’s Island",
    year: 0,
    img: ax32,
  },
];

export { books };
