import ax1 from "../assets/games/AzureStrikerGunvolt.jpg";
import ax2 from "../assets/games/Braid.jpg";
import ax3 from "../assets/games/Castlevania Symphony of the Night.jpg";
import ax4 from "../assets/games/Cave Story.jpg";
import ax5 from "../assets/games/Celeste.jpg";
import ax6 from "../assets/games/Cuphead.jpg";
import ax7 from "../assets/games/Donkey Kong Country Tropical Freeze.jpg";
import ax8 from "../assets/games/Donkey Kong Jr.jpg";
import ax9 from "../assets/games/DuckTales.jpg";
import ax10 from "../assets/games/Hollow Knight.jpg";
import ax11 from "../assets/games/Inside.jpg";
import ax12 from "../assets/games/Kirby Super Star.jpg";
import ax13 from "../assets/games/Maga Man 1.jpg";
import ax14 from "../assets/games/Maga Man 2.jpg";
import ax15 from "../assets/games/Maga Man 3.jpg";
import ax16 from "../assets/games/Mega Man X.jpg";
import ax17 from "../assets/games/Ori and The Blind Forest.jpg";
import ax18 from "../assets/games/Rayman Legends.jpg";
import ax19 from "../assets/games/Shantae Half-Genie Hero.jpg";
import ax20 from "../assets/games/Shovel Knight.jpg";
import ax21 from "../assets/games/Sonic Mania.jpg";
import ax22 from "../assets/games/Sonic the Hedgehog.jpg";
import ax23 from "../assets/games/Street Fighter II Turbo.jpg";
import ax24 from "../assets/games/Super Castlevania IV.jpg";
import ax25 from "../assets/games/Super Ghouls and Ghosts.jpg";
import ax26 from "../assets/games/Super Mario Bros 3.jpg";
import ax27 from "../assets/games/Super Mario Land 2 The Six Golden Coins.jpg";
import ax28 from "../assets/games/Super Mario World.jpg";
import ax29 from "../assets/games/Super Meat Boy.jpg";
import ax30 from "../assets/games/Tetris.jpg";
import ax31 from "../assets/games/Unravel.jpg";
import ax32 from "../assets/games/Yoshi’s Island.jpg";
import ax33 from "../assets/games/Sonic the Hedgehog 2.jpg";
import ax34 from "../assets/games/Sonic the Hedgehog 3.jpg";
import ax35 from "../assets/games/Mortal_Kombat_1.jpg";
import ax36 from "../assets/games/Mortal Kombat 2.jpg";
import ax37 from "../assets/games/Mortal_Kombat_3.jpg";
import ax38 from "../assets/games/Mortal_Kombat_4.jpg";
import ax39 from "../assets/games/Flicky.jpg";

const books = [
  {
    id: "001",
    developer: "Inti Creates",
    publisher: "Inti Creates",
    language: "",
    link: "https://en.wikipedia.org/wiki/Azure_Striker_Gunvolt",
    genre: "Action, Platform",
    title: "Azure Striker Gunvolt",
    year: 2014,
    img: ax1,
  },
  {
    id: "002",
    developer: "Number None",
    publisher: "Number None",
    language: "",
    link: "https://en.wikipedia.org/wiki/Braid_(video_game)",
    genre: "	Puzzle-Platform",
    title: "Braid",
    year: 2018,
    img: ax2,
  },
  {
    id: "003",
    developer: "Konami & Entertainment Tokyo",
    publisher: "Konami",
    language: "",
    link: "https://en.wikipedia.org/wiki/Castlevania:_Symphony_of_the_Night",
    genre: "	Action role-play, Metroidvania",
    title: "Castlevania Symphony of the Night",
    year: 1997,
    img: ax3,
  },
  {
    id: "004",
    developer: "Studio Pixel",
    publisher: "Studio Pixel",
    language: "",
    link: "https://en.wikipedia.org/wiki/Cave_Story",
    genre: "Platform-adventure, Metroidvania",
    title: "Cave Story",
    year: 2004,
    img: ax4,
  },
  {
    id: "005",
    developer: "Maddy Makes Games",
    publisher: "Maddy Makes Games",
    language: "",
    link: "https://en.wikipedia.org/wiki/Celeste_(video_game)",
    genre: "	Platform",
    title: "Celeste",
    year: 2018,
    img: ax5,
  },
  {
    id: "006",
    developer: "Studio MDHR",
    publisher: "Studio MDHR",
    language: "",
    link: "https://en.wikipedia.org/wiki/Cuphead",
    genre: "	Run and gun",
    title: "Cuphead",
    year: 2017,
    img: ax6,
  },
  {
    id: "007",
    developer: "Retro Studios",
    publisher: "Nintendo",
    language: "",
    link: "https://en.wikipedia.org/wiki/Donkey_Kong_Country:_Tropical_Freeze",
    genre: "	Platform",
    title: "Donkey Kong Country Tropical Freeze",
    year: 2014,
    img: ax7,
  },
  {
    id: "008",
    developer: "Nintendo R&D",
    publisher: "Nintendo",
    language: "",
    link: "https://en.wikipedia.org/wiki/Donkey_Kong_Jr.",
    genre: "	Platform",
    title: "Donkey Kong Jr",
    year: 1982,
    img: ax8,
  },
  {
    id: "009",
    developer: "Capcom",
    publisher: "Capcom",
    language: "",
    link: "https://en.wikipedia.org/wiki/DuckTales_(video_game)",
    genre: "	Platform",
    title: "DuckTales",
    year: 1989,
    img: ax9,
  },
  {
    id: "010",
    developer: "Team Cherry",
    publisher: "Team Cherry",
    language: "",
    link: "https://en.wikipedia.org/wiki/Hollow_Knight",
    genre: "	Metroidvania",
    title: "Hollow Knight",
    year: 2017,
    img: ax10,
  },
  {
    id: "011",
    developer: "Playdead",
    publisher: "Playdead",
    language: "",
    link: "https://en.wikipedia.org/wiki/Inside_(video_game)",
    genre: "	Puzzle-Platform",
    title: "Inside",
    year: 2016,
    img: ax11,
  },
  {
    id: "012",
    developer: "HAL Laboratory",
    publisher: "Nintendo",
    language: "",
    link: "https://en.wikipedia.org/wiki/Kirby_Super_Star",
    genre: "Action, Platform",
    title: "Kirby Super Star",
    year: 1996,
    img: ax12,
  },
  {
    id: "013",
    developer: "Capcom",
    publisher: "Capcom",
    language: "",
    link: "https://en.wikipedia.org/wiki/Mega_Man_(1987_video_game)",
    genre: "	Platform",
    title: "Maga Man 1",
    year: 1987,
    img: ax13,
  },
  {
    id: "014",
    developer: "Capcom",
    publisher: "Capcom",
    language: "",
    link: "https://en.wikipedia.org/wiki/Mega_Man_2",
    genre: "	Action, Platform",
    title: "Maga Man 2",
    year: 1988,
    img: ax14,
  },
  {
    id: "015",
    developer: "Capcom",
    publisher: "Capcom",
    language: "",
    link: "https://en.wikipedia.org/wiki/Mega_Man_3",
    genre: "	Action, Platform",
    title: "Maga Man 3",
    year: 1990,
    img: ax15,
  },
  {
    id: "016",
    developer: "Capcom",
    publisher: "Capcom",
    language: "",
    link: "https://en.wikipedia.org/wiki/Mega_Man_X",
    genre: "Action, Platform, role-playing, edutainment, Run 'n gun",
    title: "Maga Man X",
    year: 1993,
    img: ax16,
  },
  {
    id: "017",
    developer: "Moon Studios",
    publisher: "Microsoft Studios",
    language: "",
    link: "https://en.wikipedia.org/wiki/Ori_and_the_Blind_Forest",
    genre: "Platform-adventure, Metroidvania",
    title: "Ori and The Blind Forest",
    year: 2015,
    img: ax17,
  },
  {
    id: "018",
    developer: "Ubisoft",
    publisher: "Ubisoft",
    language: "",
    link: "https://en.wikipedia.org/wiki/Rayman_Legends",
    genre: "Platform",
    title: "Rayman Legendst",
    year: 2013,
    img: ax18,
  },
  {
    id: "019",
    developer: "WayForward Technologies",
    publisher: "WayForward Technologies",
    language: "",
    link: "https://en.wikipedia.org/wiki/Shantae:_Half-Genie_Hero",
    genre: "Platform",
    title: "Shantae Half-Genie Hero",
    year: 2014,
    img: ax19,
  },
  {
    id: "020",
    developer: "Yacht Club Games",
    publisher: "Yacht Club Games",
    language: "",
    link: "https://en.wikipedia.org/wiki/Shovel_Knight",
    genre: "Platform",
    title: "Shovel Knight",
    year: 2014,
    img: ax20,
  },
  {
    id: "021",
    developer: "Christian Whitehead",
    publisher: "Sega",
    language: "",
    link: "https://en.wikipedia.org/wiki/Sonic_Mania",
    genre: "Platform",
    title: "Sonic Mania",
    year: 2017,
    img: ax21,
  },
  {
    id: "022",
    developer: "Sonic Team",
    publisher: "Sega",
    language: "",
    link: "https://en.wikipedia.org/wiki/Sonic_the_Hedgehog_(1991_video_game)",
    genre: "Platform",
    title: "Sonic the Hedgehog 1",
    year: 1991,
    img: ax22,
  },
  {
    id: "023",
    developer: "Capcom",
    publisher: "Capcom",
    language: "",
    link: "https://en.wikipedia.org/wiki/Street_Fighter_II_Turbo",
    genre: "	Fighting",
    title: "Street Fighter II Turbo",
    year: 1992,
    img: ax23,
  },
  {
    id: "024",
    developer: "Konami",
    publisher: "Konami",
    language: "",
    link: "https://en.wikipedia.org/wiki/Super_Castlevania_IV",
    genre: "	Action, Platform",
    title: "Super Castlevania IV",
    year: 1991,
    img: ax24,
  },
  {
    id: "025",
    developer: "Capcom",
    publisher: "Capcom",
    language: "",
    link: "https://en.wikipedia.org/wiki/Super_Ghouls_%27n_Ghosts",
    genre: "Platform",
    title: "Super Ghouls and Ghosts",
    year: 1991,
    img: ax25,
  },
  {
    id: "026",
    developer: "Nintendo R&D",
    publisher: "Nintendo",
    language: "",
    link: "https://en.wikipedia.org/wiki/Super_Mario_Bros._3",
    genre: "Platform",
    title: "Super Mario Bros 3",
    year: 1988,
    img: ax26,
  },
  {
    id: "027",
    developer: "Nintendo R&D",
    publisher: "Nintendo",
    language: "",
    link: "https://en.wikipedia.org/wiki/Super_Mario_Land_2:_6_Golden_Coins",
    genre: "Platform",
    title: "Super Mario Land 2 The Six Golden Coins",
    year: 1992,
    img: ax27,
  },
  {
    id: "028",
    developer: "Nintendo EAD",
    publisher: "Nintendo",
    language: "",
    link: "https://en.wikipedia.org/wiki/Super_Mario_World",
    genre: "Platform",
    title: "Super Mario World",
    year: 1990,
    img: ax28,
  },
  {
    id: "029",
    developer: "Team Meat",
    publisher: "Team Meat",
    language: "",
    link: "https://en.wikipedia.org/wiki/Super_Meat_Boy",
    genre: "Platform",
    title: "Super Meat Boy",
    year: 2010,
    img: ax29,
  },
  {
    id: "030",
    developer: "Alexey Pajitnov",
    publisher: "Alexey Pajitnov",
    language: "",
    link: "https://en.wikipedia.org/wiki/Tetris",
    genre: "	Puzzle , tile-matching",
    title: "Tetris",
    year: 1985,
    img: ax30,
  },
  {
    id: "031",
    developer: "Coldwood Interactive",
    publisher: "Electronic Arts",
    language: "",
    link: "https://en.wikipedia.org/wiki/Unravel_(video_game)",
    genre: "	Puzzle-Platform",
    title: "Unravel",
    year: 2015,
    img: ax31,
  },
  {
    id: "032",
    developer: "Nintendo EAD - Nintendo R&D2 (GBA)",
    publisher: "Nintendo",
    language: "",
    link: "https://en.wikipedia.org/wiki/Yoshi%27s_Island",
    genre: "	Platform",
    title: "Yoshi’s Island",
    year: 1995,
    img: ax32,
  },

  {
    id: "033",
    developer: "Sega Technical Institute",
    publisher: "Sega",
    language: "",
    link: "https://en.wikipedia.org/wiki/Sonic_the_Hedgehog_2",
    genre: "Platform",
    title: "Sonic the Hedgehog 2",
    year: 1992,
    img: ax33,
  },

  {
    id: "034",
    developer: "Sega Technical Institute",
    publisher: "Sega",
    language: "",
    link: "https://en.wikipedia.org/wiki/Sonic_the_Hedgehog_3",
    genre: "Platform",
    title: "Sonic the Hedgehog 3",
    year: 1994,
    img: ax34,
  },
  {
    id: "035",
    developer: "Midway",
    publisher: "Midway",
    language: "",
    link: "https://en.wikipedia.org/wiki/Mortal_Kombat_%281992_video_game%29",
    genre: "Fighting",
    title: "Mortal Kombat I",
    year: 1992,
    img: ax35,
  },
  {
    id: "036",
    developer: "Midway",
    publisher: "Probe Software",
    language: "",
    link: "https://en.wikipedia.org/wiki/Mortal_Kombat_II",
    genre: "Fighting",
    title: "Mortal Kombat II",
    year: 1993,
    img: ax36,
  },
  {
    id: "037",
    developer: "Midway",
    publisher: "Midway",
    language: "",
    link: "https://en.wikipedia.org/wiki/Mortal_Kombat_3",
    genre: "Fighting",
    title: "Mortal Kombat III",
    year: 1995,
    img: ax37,
  },
  {
    id: "038",
    developer: "Midway",
    publisher: "Midway",
    language: "",
    link: "https://en.wikipedia.org/wiki/Mortal_Kombat_4",
    genre: "Fighting",
    title: "Mortal Kombat IV",
    year: 1997,
    img: ax38,
  },
  {
    id: "039",
    developer: "Sega",
    publisher: "Sega",
    language: "",
    link: "https://en.wikipedia.org/wiki/Flicky",
    genre: "Platform",
    title: "Flicky",
    year: 1984,
    img: ax39,
  },
];

export { books };
